export const categories = [
  {
    slug: 'fire-pits',
    name: 'Fire Pits & Fire Tables',
    shortName: 'Fire Pits',
    description: 'Smokeless pits, classic wood burners, fire tables, and the tools that keep the evening going.',
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1200&q=86',
  },
  {
    slug: 'cooking',
    name: 'Outdoor Cooking',
    shortName: 'Cooking',
    description: 'Cast iron, campfire cookware, grills, and everything made better over an open flame.',
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1200&q=86',
  },
  {
    slug: 'pizza-ovens',
    name: 'Pizza Ovens & Grills',
    shortName: 'Pizza & Grills',
    description: 'Backyard pizza ovens and live-fire grills made for dinner that becomes the night.',
    image: 'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1200&q=86',
  },
  {
    slug: 'furniture',
    name: 'Outdoor Furniture',
    shortName: 'Furniture',
    description: 'Gathering-ready chairs, tables, and conversation sets for the people who stay awhile.',
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=86',
  },
  {
    slug: 'heaters',
    name: 'Heaters & Lighting',
    shortName: 'Heat & Light',
    description: 'Warm light and practical heat that stretch patio season well past summer.',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=86',
  },
  {
    slug: 'outdoor-living',
    name: 'Outdoor Living',
    shortName: 'Outdoor Living',
    description: 'Blankets, hammocks, coolers, and the small comforts that make outside feel like home.',
    image: 'https://images.unsplash.com/photo-1527766833261-b09c3163a791?auto=format&fit=crop&w=1200&q=86',
  },
];

export const previewProducts = [
  {
    id: 'sg-fire-grill-32',
    handle: 'three-in-one-fire-pit-grill',
    name: '32-inch 3-in-1 Fire Pit & Grill',
    price: 179.99,
    compareAtPrice: 219.99,
    categorySlugs: ['fire-pits', 'cooking'],
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1200&q=88',
    imageAlt: 'Round wood-burning fire pit with a cooking grate',
    badge: 'FIRST-FIRE FAVORITE',
    tagline: 'Dinner first. Fire pit after.',
    description: 'A gathering-sized wood fire pit designed to move from open-flame cooking to a relaxed backyard fire without changing the centerpiece of the night.',
    details: ['32-inch gathering size', 'Removable cooking grate', 'Spark screen and weather cover', 'Wood-burning design'],
    featured: true,
    preview: true,
    availableForSale: false,
    variantId: null,
  },
  {
    id: 'sg-pizza-oven',
    handle: 'wood-fired-outdoor-pizza-oven',
    name: 'Wood-Fired Outdoor Pizza Oven',
    price: 279,
    compareAtPrice: 329,
    categorySlugs: ['pizza-ovens', 'cooking'],
    image: 'https://images.unsplash.com/photo-1579751626657-72bc17010498?auto=format&fit=crop&w=1200&q=88',
    imageAlt: 'Fresh pizza cooking beside an outdoor flame',
    badge: 'GATHERING PICK',
    tagline: 'Pizza tastes better outside.',
    description: 'A compact backyard oven for crisp, flame-kissed pizza and the kind of hands-on dinner that gives everyone a reason to gather around.',
    details: ['Fast-heating stone deck', 'Portable backyard footprint', 'Built-in temperature gauge', 'Wood-fired flavor'],
    featured: true,
    preview: true,
    availableForSale: false,
    variantId: null,
  },
  {
    id: 'sg-smokeless-pit',
    handle: 'smokeless-gathering-fire-pit',
    name: 'Smokeless Gathering Fire Pit',
    price: 169,
    compareAtPrice: 199,
    categorySlugs: ['fire-pits', 'outdoor-living'],
    image: 'https://images.unsplash.com/photo-1475483768296-6163e08872a1?auto=format&fit=crop&w=1200&q=88',
    imageAlt: 'Friends gathered around a low-smoke outdoor fire',
    badge: 'COOL-NIGHT ESSENTIAL',
    tagline: 'More flame. Less smoke in your face.',
    description: 'A portable double-wall fire pit that keeps the focus on the fire, the conversation, and the people sitting across from you.',
    details: ['Double-wall airflow', 'Portable design', 'Ash-catching base', 'Stainless steel body'],
    featured: true,
    preview: true,
    availableForSale: false,
    variantId: null,
  },
  {
    id: 'sg-pie-iron',
    handle: 'cast-iron-campfire-pie-iron',
    name: 'Cast-Iron Campfire Pie Iron',
    price: 39,
    compareAtPrice: null,
    categorySlugs: ['cooking', 'outdoor-living'],
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1200&q=88',
    imageAlt: 'Cast-iron cookware over an outdoor fire',
    badge: 'UNDER $50',
    tagline: 'The easiest way to make dessert part of the fire.',
    description: 'A long-handled cast-iron cooker for toasted sandwiches, hand pies, and late-night campfire experiments.',
    details: ['Pre-seasoned cast iron', 'Long stay-cool handles', 'Two-sided cooking', 'Made for campfires and fire pits'],
    featured: true,
    preview: true,
    availableForSale: false,
    variantId: null,
  },
  {
    id: 'sg-patio-heater',
    handle: 'quartz-flame-patio-heater',
    name: 'Quartz Flame Patio Heater',
    price: 249,
    compareAtPrice: 299,
    categorySlugs: ['heaters', 'outdoor-living'],
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=88',
    imageAlt: 'Warmly lit outdoor patio at dusk',
    badge: 'EXTEND THE SEASON',
    tagline: 'Keep the patio open after the temperature drops.',
    description: 'A visible-flame patio heater that adds warmth and atmosphere without turning the gathering into a utility project.',
    details: ['Quartz glass flame tube', 'Tip-over safety shutoff', 'Rolling base', 'Outdoor-rated finish'],
    featured: false,
    preview: true,
    availableForSale: false,
    variantId: null,
  },
  {
    id: 'sg-adirondack-chair',
    handle: 'adirondack-gathering-chair',
    name: 'Adirondack Gathering Chair',
    price: 189,
    compareAtPrice: 229,
    categorySlugs: ['furniture', 'outdoor-living'],
    image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=88',
    imageAlt: 'Comfortable outdoor seating arranged for conversation',
    badge: 'PATIO CLASSIC',
    tagline: 'The seat everyone drags closer to the fire.',
    description: 'A wide, laid-back outdoor chair built around the posture of a long conversation and one more log on the fire.',
    details: ['Weather-ready construction', 'Wide arms for drinks and plates', 'Contoured back', 'Simple seasonal care'],
    featured: false,
    preview: true,
    availableForSale: false,
    variantId: null,
  },
  {
    id: 'sg-dutch-oven',
    handle: 'cast-iron-camp-dutch-oven',
    name: 'Cast-Iron Camp Dutch Oven',
    price: 89,
    compareAtPrice: 109,
    categorySlugs: ['cooking'],
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=1200&q=88',
    imageAlt: 'Cast-iron outdoor cookware with a hearty meal',
    badge: 'FIRE COOKING',
    tagline: 'One pot. A whole night of possibilities.',
    description: 'Heavy cast iron for slow-cooked chili, cobbler, bread, and everything that smells better when it comes off the coals.',
    details: ['Pre-seasoned cast iron', 'Flanged lid holds coals', 'Bail handle', 'Campfire-ready legs'],
    featured: false,
    preview: true,
    availableForSale: false,
    variantId: null,
  },
  {
    id: 'sg-firewood-carrier',
    handle: 'waxed-canvas-firewood-carrier',
    name: 'Waxed Canvas Firewood Carrier',
    price: 44,
    compareAtPrice: null,
    categorySlugs: ['fire-pits', 'outdoor-living'],
    image: 'https://images.unsplash.com/photo-1527766833261-b09c3163a791?auto=format&fit=crop&w=1200&q=88',
    imageAlt: 'Rugged outdoor gear beside a lakeside chair',
    badge: 'FIRE-SIDE GEAR',
    tagline: 'Fewer trips. Less bark through the house.',
    description: 'A rugged, open-ended carrier that keeps an armload together from the woodpile to the hearth or backyard pit.',
    details: ['Waxed canvas body', 'Reinforced carry handles', 'Open-ended loading', 'Folds flat for storage'],
    featured: false,
    preview: true,
    availableForSale: false,
    variantId: null,
  },
];

export function getCategory(slug) {
  return categories.find((category) => category.slug === slug);
}

export function formatPrice(value, currencyCode = 'USD') {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: currencyCode,
    minimumFractionDigits: value % 1 === 0 ? 0 : 2,
  }).format(value);
}
